### ISSUE TITLE
PublishTestResults Task fails

### ISSUE THREAD

**Issue by diskmanti** [clemlesne/azure-pipelines-agent#166]
The official task from Azure to publish test results fails. This happens because the task checks if dotnet is installed by running the command `dotnet --version`. This arg is not available in the dotnetcore package installed in the image of the runner.
```log
/usr/bin/dotnet --version
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application '--version' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.
```

**Comment by clemlesne** [comment]
I understand you are trying to run a task using in backend .NET CLI. The task tries to run `/usr/bin/dotnet --version`, which fails.

Questions:

- Is any task using .NET Core working fine before this one?
- Can you please give me details about the project version and container distro you are using?

**Comment by diskmanti** [comment]
Hello @clemlesne 

thank you for your feedback. I managed to solve this by manually installing the required SDK for dotnet:

```yaml
           - bash: |
               microdnf remove aspnetcore-runtime-6.0
               microdnf install dotnet-sdk-8.0
               microdnf install dotnet-runtime-8.0
             displayName: :Install > Runtime

           - task: PublishTestResults@2
             inputs:
               testResultsFormat: 'JUnit'
               testResultsFiles: 'CheckovReport.xml'
               failTaskOnFailureToPublishResults: true
               failTaskOnMissingResultsFile: true
               testRunTitle: 'Checkov Results'
             displayName: "Publish > Checkov scan results"
```

Regarding your questions:
- None of the dotnet tasks were working
- I installed the latest helm chart and I am using the ubi8 image
- I am using the [PublishResults task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-test-results-v2?view=azure-pipelines&tabs=trx%2Ctrxattachments%2Cyaml) from Azure and the [GitTools custom tasks](https://marketplace.visualstudio.com/items?itemName=gittools.gittools)
- Pipelines yaml definitions is as follows:
```yaml
# Terraform pipeline

trigger:
  - main

variables:
  tf_version: "latest" # what version of terraform should be used
  cost_increase_alert_percentage: 50 # if the difference in costs is higher than x% then you will need to manually validate the deployment

pool:
  name: "test"

stages:
  # Run Checkov, upload results and optionally halt if there any problems found
  ######################################################################

  - stage: "runCheckov"
    displayName: "Checkov - Scan Terraform files"
    jobs:
      - job: "runCheckov"
        displayName: "Checkov > Pull, run and publish results of Checkov scan"
        steps:
          - bash: |
              python -m pip install checkov
              echo $PWD
            workingDirectory: $(System.DefaultWorkingDirectory)
            displayName: "Install  > bridgecrew/checkov"
          - bash: |
              checkov --file *.tf . --output junitxml --soft-fail > $(System.DefaultWorkingDirectory)/CheckovReport.xml
              echo $PWD
              ls -lah .
            workingDirectory: $(System.DefaultWorkingDirectory)
            displayName: :Run > Checkov"
          - bash: |
              microdnf remove aspnetcore-runtime-6.0
              microdnf install dotnet-sdk-8.0
              microdnf install dotnet-runtime-8.0
            displayName: :Install > Runtime

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: 'CheckovReport.xml'
              failTaskOnFailureToPublishResults: true
              failTaskOnMissingResultsFile: true
              testRunTitle: 'Checkov Results'
            displayName: "Publish > Checkov scan results"
```

Hope this is helpful,
Thank you
