### ISSUE TITLE
[Question] How to set key value capability?

### ISSUE THREAD

**Issue by ghost** [clemlesne/azure-pipelines-agent#308]
Documentation mentions how to set a single value capability here - https://clemlesne.github.io/blue-agent/docs/advanced-topics/capabilities/#example-arm64-agents. 
```
pipelines:
  poolName: private_kube
  capabilities:
    - arch_arm64
```

However, there is no mention of how to set a capability where key is `arch` and value is `arm64`. Is this possible?
