### ISSUE TITLE
Feature: `AZP_AGENT_NAME` as an optional parameter

### ISSUE THREAD

**Issue by archerixx** [clemlesne/azure-pipelines-agent#4]
Since I was unable to create replicas with Helm, I am trying to implement Azure agent through Docker image (ghcr.io/clemlesne/azure-pipelines-agent:ubi8-main). 
I am failing to create replicas this way, since AZP_AGENT_NAME is required and each replica would then take same from ENV.

Would you be able to make it optional, so AZP_AGENT_NAME takes initialy Pod name so each replica would be agent for itself ?
Also, if this is bad idea beacuse of optimization, then you can ignore this request.
Thanks.

**Comment by clemlesne** [comment]
Seems related to https://github.com/clemlesne/azure-pipelines-agent/issues/5.

**Comment by clemlesne** [comment]
As an explanation, it is excepted to require the env variable to be defined externally. It provides the advantage to be defined at container level.

Main (first) agent:

```yaml
env:
  - name: AZP_AGENT_NAME
    value: "[instance name]-template"
```

Other agents:

```yaml
env:
  - name: AZP_AGENT_NAME
    value: "[pod hostname]"
```

I hope it is clearer.

If not, can you explain precisely your use-case and your motivations?
